package gui;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Guest.java
 *
 * Created on Mar 26, 2013, 7:11:37 PM
 */
/**
 *
 * @author Sumapig_VAIO
 */
public class Guest extends javax.swing.JFrame {

    /** Creates new form Guest */
    public Guest() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnGroup1 = new javax.swing.ButtonGroup();
        btnGroup2 = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jTextField6comforter = new javax.swing.JTextField();
        jTextField4pillows = new javax.swing.JTextField();
        jLabel17bed = new javax.swing.JLabel();
        jLabel16comforter = new javax.swing.JLabel();
        jLabel14pillows = new javax.swing.JLabel();
        jTextField8email = new javax.swing.JTextField();
        jLabel9email = new javax.swing.JLabel();
        jLabel8contact = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton2backhome = new javax.swing.JButton();
        jLabel10booking = new javax.swing.JLabel();
        jButton1book = new javax.swing.JButton();
        jLabel11roomtype = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        label1personal = new java.awt.Label();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField9bed = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel1date = new javax.swing.JLabel();
        jTextField1date = new javax.swing.JTextField();
        jLabel2name = new javax.swing.JLabel();
        jTextField2name = new javax.swing.JTextField();
        jLabel3address = new javax.swing.JLabel();
        jTextField3address = new javax.swing.JTextField();
        jLabel5age = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField5age = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        rdrFemale = new javax.swing.JRadioButton();
        rdrMale = new javax.swing.JRadioButton();
        jLabel15bookinginfo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13addresstop = new javax.swing.JLabel();
        jLabel8image = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();

        jLabel4.setText("jLabel4");

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField6comforter.setBounds(540, 550, 35, 30);
        jLayeredPane1.add(jTextField6comforter, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField4pillows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4pillowsActionPerformed(evt);
            }
        });
        jTextField4pillows.setBounds(540, 510, 35, 30);
        jLayeredPane1.add(jTextField4pillows, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel17bed.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel17bed.setText("Bed");
        jLabel17bed.setBounds(470, 590, 32, 16);
        jLayeredPane1.add(jLabel17bed, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel16comforter.setFont(new java.awt.Font("Arial", 0, 14));
        jLabel16comforter.setText("Comforter");
        jLabel16comforter.setBounds(470, 550, 74, 34);
        jLayeredPane1.add(jLabel16comforter, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel14pillows.setFont(new java.awt.Font("Arial", 0, 14));
        jLabel14pillows.setText("Pillows");
        jLabel14pillows.setBounds(470, 520, 56, 22);
        jLayeredPane1.add(jLabel14pillows, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField8email.setFont(new java.awt.Font("Arial", 0, 14));
        jTextField8email.setBounds(260, 420, 374, 26);
        jLayeredPane1.add(jTextField8email, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel9email.setFont(new java.awt.Font("Arial", 0, 14));
        jLabel9email.setForeground(new java.awt.Color(255, 255, 51));
        jLabel9email.setText("E-mail Address");
        jLabel9email.setBounds(130, 420, 121, 21);
        jLayeredPane1.add(jLabel9email, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8contact.setFont(new java.awt.Font("Arial", 0, 14));
        jLabel8contact.setForeground(new java.awt.Color(255, 255, 51));
        jLabel8contact.setText("Contact Number");
        jLabel8contact.setBounds(130, 380, 123, 26);
        jLayeredPane1.add(jLabel8contact, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jTextField7.setBounds(260, 380, 215, 27);
        jLayeredPane1.add(jTextField7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2backhome.setFont(new java.awt.Font("Arial", 0, 14));
        jButton2backhome.setText("BACK TO HOME");
        jButton2backhome.setBounds(580, 660, 149, 38);
        jLayeredPane1.add(jButton2backhome, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel10booking.setFont(new java.awt.Font("Calvin", 0, 36));
        jLabel10booking.setForeground(new java.awt.Color(255, 255, 51));
        jLabel10booking.setText("BOOKING RESERVATION");
        jLabel10booking.setBounds(280, 30, 480, 50);
        jLayeredPane1.add(jLabel10booking, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1book.setFont(new java.awt.Font("Arial", 0, 14));
        jButton1book.setText("BOOK");
        jButton1book.setBounds(380, 660, 132, 37);
        jLayeredPane1.add(jButton1book, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel11roomtype.setFont(new java.awt.Font("Arial", 0, 14));
        jLabel11roomtype.setText("Room Type");
        jLabel11roomtype.setBounds(180, 490, 75, 28);
        jLayeredPane1.add(jLabel11roomtype, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator2.setBounds(130, 460, 826, 14);
        jLayeredPane1.add(jSeparator2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        label1personal.setAlignment(java.awt.Label.CENTER);
        label1personal.setBackground(new java.awt.Color(0, 0, 0));
        label1personal.setFont(new java.awt.Font("Berlin Sans FB", 0, 24));
        label1personal.setForeground(new java.awt.Color(51, 255, 204));
        label1personal.setText("Personal Information");
        label1personal.setBounds(130, 150, 220, 32);
        jLayeredPane1.add(label1personal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator1.setBounds(130, 130, 824, 10);
        jLayeredPane1.add(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jTextField9bed.setBounds(540, 590, 36, 30);
        jLayeredPane1.add(jTextField9bed, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel12.setForeground(new java.awt.Color(255, 255, 51));
        jLabel12.setText("Contact Number: +639205643442");
        jLabel12.setBounds(420, 80, 261, 19);
        jLayeredPane1.add(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnGroup2.add(jCheckBox5);
        jCheckBox5.setFont(new java.awt.Font("Arial", 0, 14));
        jCheckBox5.setForeground(new java.awt.Color(255, 255, 51));
        jCheckBox5.setText("Duplex");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        jCheckBox5.setBounds(260, 620, 70, 20);
        jLayeredPane1.add(jCheckBox5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnGroup2.add(jCheckBox2);
        jCheckBox2.setFont(new java.awt.Font("Arial", 0, 14));
        jCheckBox2.setForeground(new java.awt.Color(255, 255, 51));
        jCheckBox2.setText("Sweet");
        jCheckBox2.setBounds(260, 560, 63, 20);
        jLayeredPane1.add(jCheckBox2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnGroup2.add(jCheckBox1);
        jCheckBox1.setFont(new java.awt.Font("Arial", 0, 14));
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 51));
        jCheckBox1.setText("Deluxe");
        jCheckBox1.setBounds(260, 534, 70, 20);
        jLayeredPane1.add(jCheckBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnGroup2.add(jCheckBox4);
        jCheckBox4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(255, 255, 51));
        jCheckBox4.setText("Single");
        jCheckBox4.setBounds(260, 505, 70, 20);
        jLayeredPane1.add(jCheckBox4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnGroup2.add(jCheckBox3);
        jCheckBox3.setFont(new java.awt.Font("Arial", 0, 14));
        jCheckBox3.setForeground(new java.awt.Color(255, 255, 51));
        jCheckBox3.setText("Matrimonal");
        jCheckBox3.setToolTipText("");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jCheckBox3.setBounds(260, 590, 95, 20);
        jLayeredPane1.add(jCheckBox3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1date.setFont(new java.awt.Font("Arial", 0, 14));
        jLabel1date.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1date.setText("Date:");
        jLabel1date.setBounds(130, 210, 42, 23);
        jLayeredPane1.add(jLabel1date, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField1date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1dateActionPerformed(evt);
            }
        });
        jTextField1date.setBounds(260, 210, 96, 25);
        jLayeredPane1.add(jTextField1date, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2name.setFont(new java.awt.Font("Arial", 0, 14));
        jLabel2name.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2name.setText("Name");
        jLabel2name.setBounds(130, 240, 54, 24);
        jLayeredPane1.add(jLabel2name, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jTextField2name.setBounds(260, 240, 288, 28);
        jLayeredPane1.add(jTextField2name, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3address.setFont(new java.awt.Font("Arial", 0, 14));
        jLabel3address.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3address.setText("Address");
        jLabel3address.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jLabel3address.setBounds(130, 270, 70, 29);
        jLayeredPane1.add(jLabel3address, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jTextField3address.setBounds(260, 280, 568, 27);
        jLayeredPane1.add(jTextField3address, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5age.setFont(new java.awt.Font("Arial", 0, 14));
        jLabel5age.setForeground(new java.awt.Color(255, 255, 51));
        jLabel5age.setText("Age");
        jLabel5age.setToolTipText("");
        jLabel5age.setBounds(130, 350, 56, 25);
        jLayeredPane1.add(jLabel5age, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14));
        jLabel7.setForeground(new java.awt.Color(255, 255, 51));
        jLabel7.setText("Gender");
        jLabel7.setBounds(130, 320, 61, 21);
        jLayeredPane1.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jTextField5age.setBounds(260, 350, 54, 22);
        jLayeredPane1.add(jTextField5age, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSeparator3.setBounds(130, 650, 814, 10);
        jLayeredPane1.add(jSeparator3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnGroup1.add(rdrFemale);
        rdrFemale.setFont(new java.awt.Font("Arial", 0, 14));
        rdrFemale.setText("Female");
        rdrFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdrFemaleActionPerformed(evt);
            }
        });
        rdrFemale.setBounds(260, 320, 73, 25);
        jLayeredPane1.add(rdrFemale, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnGroup1.add(rdrMale);
        rdrMale.setFont(new java.awt.Font("Arial", 0, 14));
        rdrMale.setText("Male");
        rdrMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdrMaleActionPerformed(evt);
            }
        });
        rdrMale.setBounds(440, 320, 55, 25);
        jLayeredPane1.add(rdrMale, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel15bookinginfo.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15bookinginfo.setFont(new java.awt.Font("Berlin Sans FB", 0, 24));
        jLabel15bookinginfo.setForeground(new java.awt.Color(51, 255, 204));
        jLabel15bookinginfo.setText("Booking Information");
        jLabel15bookinginfo.setBounds(130, 470, 485, 27);
        jLayeredPane1.add(jLabel15bookinginfo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 16));
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Additionals");
        jLabel1.setBounds(470, 490, 100, 20);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel13addresstop.setFont(new java.awt.Font("Arial", 0, 12));
        jLabel13addresstop.setForeground(new java.awt.Color(255, 255, 102));
        jLabel13addresstop.setText("Address: Deluxe St. Near IT Park , Tacloban City");
        jLabel13addresstop.setBounds(390, 100, 315, 15);
        jLayeredPane1.add(jLabel13addresstop, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8image.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sumapig_VAIO\\Desktop\\21.jpg")); // NOI18N
        jLabel8image.setBounds(-120, 0, 1610, 770);
        jLayeredPane1.add(jLabel8image, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jSlider1.setBounds(760, 150, 200, 23);
        jLayeredPane1.add(jSlider1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jCheckBox3ActionPerformed

private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jCheckBox5ActionPerformed

private void jTextField1dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1dateActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextField1dateActionPerformed

private void jTextField4pillowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4pillowsActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextField4pillowsActionPerformed

private void rdrMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdrMaleActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_rdrMaleActionPerformed

private void rdrFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdrFemaleActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_rdrFemaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Guest().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroup1;
    private javax.swing.ButtonGroup btnGroup2;
    private javax.swing.JButton jButton1book;
    private javax.swing.JButton jButton2backhome;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10booking;
    private javax.swing.JLabel jLabel11roomtype;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13addresstop;
    private javax.swing.JLabel jLabel14pillows;
    private javax.swing.JLabel jLabel15bookinginfo;
    private javax.swing.JLabel jLabel16comforter;
    private javax.swing.JLabel jLabel17bed;
    private javax.swing.JLabel jLabel1date;
    private javax.swing.JLabel jLabel2name;
    private javax.swing.JLabel jLabel3address;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5age;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8contact;
    private javax.swing.JLabel jLabel8image;
    private javax.swing.JLabel jLabel9email;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField1date;
    private javax.swing.JTextField jTextField2name;
    private javax.swing.JTextField jTextField3address;
    private javax.swing.JTextField jTextField4pillows;
    private javax.swing.JTextField jTextField5age;
    private javax.swing.JTextField jTextField6comforter;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8email;
    private javax.swing.JTextField jTextField9bed;
    private java.awt.Label label1personal;
    private javax.swing.JRadioButton rdrFemale;
    private javax.swing.JRadioButton rdrMale;
    // End of variables declaration//GEN-END:variables
}
