package gui;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GUIForm.java
 *
 * Created on Mar 26, 2013, 2:15:03 PM
 */
/**
 *
 * @author Sumapig_VAIO
 */
public class GUIForm extends javax.swing.JFrame {

    /** Creates new form GUIForm */
    public GUIForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1admin = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2pass = new javax.swing.JLabel();
        jLabel3hotelres = new javax.swing.JLabel();
        jButton1login = new javax.swing.JButton();
        jButton2cancel = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1admin.setFont(new java.awt.Font("David", 0, 24));
        jLabel1admin.setForeground(new java.awt.Color(255, 255, 102));
        jLabel1admin.setText("ADMIN");
        jLabel1admin.setBounds(270, 230, 112, 25);
        jLayeredPane1.add(jLabel1admin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField1.setFont(new java.awt.Font("Arial", 0, 18));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.setBounds(450, 218, 236, 30);
        jLayeredPane1.add(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2pass.setFont(new java.awt.Font("David", 0, 24));
        jLabel2pass.setForeground(new java.awt.Color(255, 255, 102));
        jLabel2pass.setText("PASSWORD");
        jLabel2pass.setBounds(270, 280, 170, 25);
        jLayeredPane1.add(jLabel2pass, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3hotelres.setFont(new java.awt.Font("Calvin", 0, 48));
        jLabel3hotelres.setForeground(new java.awt.Color(255, 255, 102));
        jLabel3hotelres.setText("Hotel Reservation");
        jLabel3hotelres.setBounds(200, 30, 621, 124);
        jLayeredPane1.add(jLabel3hotelres, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1login.setFont(new java.awt.Font("Bauhaus 93", 0, 18));
        jButton1login.setText("LOGIN");
        jButton1login.setBounds(300, 370, 132, 48);
        jLayeredPane1.add(jButton1login, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2cancel.setFont(new java.awt.Font("Bauhaus 93", 0, 18));
        jButton2cancel.setText("CANCEL");
        jButton2cancel.setBounds(540, 370, 120, 48);
        jLayeredPane1.add(jButton2cancel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPasswordField1.setFont(new java.awt.Font("Arial", 0, 18));
        jPasswordField1.setBounds(450, 280, 236, 30);
        jLayeredPane1.add(jPasswordField1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setFont(new java.awt.Font("Elephant", 0, 18));
        jLabel1.setForeground(new java.awt.Color(255, 255, 51));
        jLabel1.setText("Developers:");
        jLabel1.setBounds(30, 260, 160, 30);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14));
        jLabel2.setForeground(new java.awt.Color(255, 255, 102));
        jLabel2.setText("Kim Geraldine Fabe");
        jLabel2.setBounds(10, 290, 150, 20);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14));
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("Mel Anthony Inot");
        jLabel3.setBounds(20, 310, 130, 19);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14));
        jLabel4.setForeground(new java.awt.Color(255, 255, 102));
        jLabel4.setText("Maria Kay Ren Sumapig");
        jLabel4.setBounds(0, 330, 180, 19);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14));
        jLabel5.setForeground(new java.awt.Color(255, 255, 51));
        jLabel5.setText("Jose Rey Villanueva");
        jLabel5.setBounds(20, 350, 160, 19);
        jLayeredPane1.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabel8.setBounds(180, 160, 600, 360);
        jLayeredPane1.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabel6.setBounds(180, 40, 600, 100);
        jLayeredPane1.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Sumapig_VAIO\\Desktop\\56.jpg")); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.setBounds(-780, -480, 1910, 1120);
        jLayeredPane1.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 955, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new GUIForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1login;
    private javax.swing.JButton jButton2cancel;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1admin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel2pass;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel3hotelres;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
