package gui;
import javax.swing.JOptionPane;

public class LogIn extends javax.swing.JFrame {

    /** Creates new form GUIForm */
    public LogIn() 
    {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        adminTxt = new javax.swing.JTextField();
        adminLabl = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();
        logBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pwLabl = new javax.swing.JLabel();
        pwTxt = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adminTxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        adminTxt.setBounds(200, 120, 236, 38);
        jLayeredPane1.add(adminTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);

        adminLabl.setFont(new java.awt.Font("David", 0, 24)); // NOI18N
        adminLabl.setText("ADMIN");
        adminLabl.setBounds(60, 130, 112, 25);
        jLayeredPane1.add(adminLabl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cancelBtn.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        cancelBtn.setText("CANCEL");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        cancelBtn.setBounds(270, 260, 120, 48);
        jLayeredPane1.add(cancelBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        logBtn.setFont(new java.awt.Font("Bauhaus 93", 0, 18)); // NOI18N
        logBtn.setText("LOGIN");
        logBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logBtnActionPerformed(evt);
            }
        });
        logBtn.setBounds(90, 260, 132, 48);
        jLayeredPane1.add(logBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("French Script MT", 3, 48)); // NOI18N
        jLabel3.setText("M~A RH Login");
        jLabel3.setBounds(80, 20, 330, 77);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        pwLabl.setFont(new java.awt.Font("David", 0, 24)); // NOI18N
        pwLabl.setText("PASSWORD");
        pwLabl.setBounds(40, 200, 129, 25);
        jLayeredPane1.add(pwLabl, javax.swing.JLayeredPane.DEFAULT_LAYER);

        pwTxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pwTxt.setBounds(200, 190, 236, 39);
        jLayeredPane1.add(pwTxt, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/login.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBounds(-36, -16, 540, 380);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logBtnActionPerformed
        if(adminTxt.getText().equals("admin") && pwTxt.getText().toString().equals("admin")){
            Home view1 = new Home(this, true);
            view1.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(this, "Invalid Admin or Password, please register to secure ur account.");
        }
    }//GEN-LAST:event_logBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminLabl;
    private javax.swing.JTextField adminTxt;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton logBtn;
    private javax.swing.JLabel pwLabl;
    private javax.swing.JPasswordField pwTxt;
    // End of variables declaration//GEN-END:variables
}
