package gui;

import controller.HotelDAO;
import entity.Guest;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class ViewRes extends javax.swing.JFrame {
    
    DefaultTableModel mod = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column){
            return false;
        }
    };
    
    public ViewRes(){
        initComponents();
        setTable();
        setTable("SELECT * FROM guestlist;");
    }

    public void setTable(){
        mod.addColumn("Name");
        mod.addColumn("Address");
        mod.addColumn("Gender");
        mod.addColumn("Date Booked");
        mod.addColumn("Age");
        mod.addColumn("Contacts");
        mod.addColumn("Email");
        mod.addColumn("Room Type");
        mod.addColumn("Room Num");
        mod.addColumn("Check-IN");
        mod.addColumn("Chech-OUT");
        mod.addColumn("Number of Occupants");
        tblBookers.setModel(mod);
    }
    
    public void setTable(String sql){
        try{
            HotelDAO action = new HotelDAO();
            ArrayList<Guest> list = action.getBookFlightInfos(sql);
            
            if (mod.getRowCount() > 0) {
                for(int row=mod.getRowCount(); row > 0; row --){
                    mod.removeRow(row-1);
                }
                
                for (int i=0; i<list.size(); i++){
                    Guest info = list.get(i);
                    Object[] obj = new Object[]{info.getName(), info.getAddress(), info.getGender(), info.getDate(), info.getAge(), info.getContacts(),
                    info.getEmail(), info.getRoomtype(), info.getRoomnum(), info.getCheckin(),
                    info.getCheckout(), info.getOccupynum()};
                    mod.addRow(obj);
  
                }
            } else{
                for(int i=0; i <list.size(); i++){
                    Guest info = list.get(i);
                     Object[] obj = new Object[]{info.getName(), info.getAddress(), info.getGender(), info.getDate(), info.getAge(), info.getContacts(),
                    info.getEmail(), info.getRoomtype(), info.getRoomnum(), info.getCheckin(),
                    info.getCheckout(), info.getOccupynum()};
                    mod.addRow(obj);
                }
            } tblBookers.setModel(mod);
            
        }catch (Exception e){
            System.out.println(e);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBookers = new javax.swing.JTable();
        cancelRes = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblBookers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblBookers);

        jScrollPane1.setBounds(10, 10, 840, 420);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cancelRes.setText("Cancel Reservation");
        cancelRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelResActionPerformed(evt);
            }
        });
        cancelRes.setBounds(320, 440, 130, 30);
        jLayeredPane1.add(cancelRes, javax.swing.JLayeredPane.DEFAULT_LAYER);

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });
        exitBtn.setBounds(470, 440, 90, 30);
        jLayeredPane1.add(exitBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelResActionPerformed
  /**      HotelDAO action = new HotelDAO();
        try{
            action.deleteRes("DELETE FROM guestlist WHERE Name=" + tblBookers.getValueAt(tblBookers.getSelectedRow(), 0) + ";");
            JOptionPane.showMessageDialog(this, "Reservation cancelled.");
            setTable("SELECT * FROM guestlist;");
        }catch(Exception e){
            System.out.println(e);
        } **/
    }//GEN-LAST:event_cancelResActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewRes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewRes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewRes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewRes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Reservation().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelRes;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBookers;
    // End of variables declaration//GEN-END:variables

}
