/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ViewBooks.java
 *
 * Created on Mar 31, 2013, 7:53:03 AM
 */
package gui;

import DAO.HotelDAO;
import entity.Guest;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chan 'n' Villanueva
 */
public class ViewBooks extends javax.swing.JDialog {

    /** Creates new form ViewBooks */
    DefaultTableModel mod = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column){
            return false;
        }
    };
    
    public ViewBooks(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        setTable();
        setTable("SELECT * FROM guestlist;");
    }
    
    public void setTable(){
        mod.addColumn("Name");
        mod.addColumn("Address");
        mod.addColumn("Date");
        mod.addColumn("E-mail");
        mod.addColumn("Room #");
        mod.addColumn("Room Type");
        mod.addColumn("Check-IN");
        mod.addColumn("Check-OUT");
        tblBooks.setModel(mod);
    }
    
    public void setTable(String sql){
        try{
            HotelDAO action = new HotelDAO();
            ArrayList<Guest> list = action.getBookFlightInfos(sql);

            if (mod.getRowCount() > 0){
                for (int row = mod.getRowCount(); row > 0; row--){
                    mod.removeRow(row-1);
                }
                for(int i = 0 ; i < list.size(); i++){
                    Guest info = list.get(i);
                    
                    Object[] obj = new Object[]{info.getName(), info.getAddress(),
                                info.getDate(), info.getEmail(), info.getRoomtype(),
                                info.getRoomnum(), info.getCheckin(), info.getCheckout()};
                    mod.addRow(obj);
                }
            }else{
                for(int i = 0 ; i < list.size(); i++){
                    Guest info = list.get(i);
                    
                    Object[] obj = new Object[]{info.getName(), info.getAddress(),
                                info.getDate(), info.getEmail(), info.getRoomtype(),
                                info.getRoomnum(), info.getCheckin(), info.getCheckout()};
                    mod.addRow(obj);
                }
            }tblBooks.setModel(mod);

        }catch(Exception e){
            System.out.println(e);
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBooks = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        cmbViewQuery = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        lblBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblBooks);

        jScrollPane1.setBounds(10, 110, 770, 270);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Searching for Something?..", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.TOP));

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        cmbViewQuery.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Name", "Address", "Date", "E-mail", "Room Type", "Room #", "Check-IN", "Check-OUT" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(cmbViewQuery, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbViewQuery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel1.setBounds(10, 20, 380, 80);
        jLayeredPane1.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("Vivaldi", 3, 28));
        jLabel2.setText("Maria~Antonio Resort Hotel");
        jLabel2.setBounds(400, 20, 380, 70);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        lblBG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/view.jpg"))); // NOI18N
        lblBG.setText("jLabel1");
        lblBG.setBounds(4, 4, 790, 390);
        jLayeredPane1.add(lblBG, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
// TODO add your handling code here:
    String value = cmbViewQuery.getSelectedItem().toString();
    if(value.equals("Name")){
        setTable("SELECT * FROM guestlist WHERE Name like '%" + txtSearch.getText() + "%';");
    }else if(value.equals("Address")){
        setTable("SELECT * FROM guestlist WHERE Address like '%" + txtSearch.getText() + "%';");
    }else if(value.equals("Date")){
        setTable("SELECT * FROM guestlist WHERE Date like '%" + txtSearch.getText() + "%';");
    }else if(value.equals("E-mail")){
        setTable("SELECT * FROM guestlist WHERE Email like '%" + txtSearch.getText() + "%';");
    }else if(value.equals("Room Type")){
        setTable("SELECT * FROM guestlist WHERE RoomType like '%" + txtSearch.getText() + "%';");
    }else if(value.equals("Room #")){
        setTable("SELECT * FROM guestlist WHERE RoomNum like '%" + txtSearch.getText() + "%';");
    }else if(value.equals("Check-IN")){
        setTable("SELECT * FROM guestlist WHERE CheckIn like '%" + txtSearch.getText() + "%';");
    }else if(value.equals("Check-OUT")){
        setTable("SELECT * FROM guestlist WHERE CheckOut like '%" + txtSearch.getText() + "%';");
    }
}//GEN-LAST:event_txtSearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                ViewBooks dialog = new ViewBooks(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbViewQuery;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBG;
    private javax.swing.JTable tblBooks;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

}
